In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
API_KEY = 'xxx'
BASE_URL = 'https://api.meetup.com'

In [8]:
# get events
urlname = 'DS-ProD-SF'

events_url = BASE_URL + '/' + urlname + '/events'
params = {'sign':'true','key': API_KEY, 'status': 'past'}
response = requests.get(events_url, params = params)
events = response.json()

len(events)
event_ids = []
event_desc_raw= []

for event in events:
    event_ids.append(event['id'])
    event_desc_raw.append(event['description'])

event_description = []
for i in xrange(len(event_ids)):
    soup = BeautifulSoup(event_desc_raw[i], 'html.parser')
    event_description.append(soup.get_text())
    
df_events= pd.DataFrame([event_ids, event_description]).T
df_events.columns = ['event_id', 'event_description']
df_events

    event_id                                  event_description
0  221309453  You've heard of Pair Programming: Introducing ...
1  221430964  No it isn't Pair Programming.. It's "Pair Data...
2  221619965  No it isn't Pair Programming.. It's "Pair Data...
3  221911630  No it isn't Pair Programming.. It's "Pair Data...
4  222155922  No it isn't Pair Programming.. It's "Pair Data...
5  222592383  No it isn't Pair Programming.. It's "Pair Data...
6  224334581  Get advice for ramping up your Data Science sk...
7  224498084  A panel discussion on best practices for growi...
8  224916731  How does entering a bootcamp or Masters progra...

In [9]:
# get rsvps

member_id = []
event_id = []

for i in event_ids:
    rsvps_url = BASE_URL + '/' + urlname +'/events/' + i + '/rsvps'
    params = {'sign':'true','key': API_KEY}
    response = requests.get(rsvps_url, params = params)
    rsvps = response.json()
    
    for rsvp in rsvps:
        member_id.append(rsvp['member']['id'])
        event_id.append(rsvp['event']['id'])
               
df_rsvps = pd.DataFrame([member_id, event_id]).T
df_rsvps.columns = ['member_id', 'event_id']
df_rsvps

     member_id   event_id
0     87429312  221309453
1     13362819  221309453
2    131164762  221309453
3     13109669  221309453
4     93515872  221309453
5      2966361  221309453
6    152101752  221309453
7      8645227  221309453
8     10913384  221309453
9    126930932  221309453
10    12580731  221309453
11   171094422  221309453
12    61117372  221309453
13   102574092  221309453
14    92361642  221309453
15     3881071  221309453
16     5729595  221309453
17   104495652  221309453
18   150131522  221309453
19   162954412  221309453
20    87429312  221430964
21    11103435  221430964
22   158779462  221430964
23    12243839  221430964
24    93515872  221430964
25   184179092  221430964
26   143070232  221430964
27   125514252  221430964
28      327482  221430964
29   110134802  221430964
..         ...        ...
520  159490792  224916731
521   96744352  224916731
522   59595312  224916731
523   13629527  224916731
524  192495024  224916731
525  184556461  224916731
526  192315146  224916731
527   50412492  224916731
528  187899709  224916731
529   13361447  224916731
530  182667296  224916731
531    3881071  224916731
532   10978618  224916731
533  151154102  224916731
534    9789480  224916731
535  181883622  224916731
536  184519851  224916731
537  191020372  224916731
538  162260602  224916731
539  192182636  224916731
540  176226512  224916731
541  187202519  224916731
542   63486122  224916731
543  192721871  224916731
544   89894632  224916731
545   66798272  224916731
546  187050989  224916731
547  184957854  224916731
548   14522782  224916731
549  131968622  224916731

[550 rows x 2 columns]

In [10]:
# member + event
df = pd.merge(df_events, df_rsvps, on = 'event_id')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 550 entries, 0 to 549
Data columns (total 3 columns):
event_id             550 non-null object
event_description    550 non-null object
member_id            550 non-null object
dtypes: object(3)
memory usage: 17.2+ KB

In [12]:
df.to_json('data2.json')